### ISSUE TITLE
Bug: `Bearer` prefix is not allowed in auth header

### ISSUE THREAD

**Issue by jtfidje** [starlite-api/starlite-jwt#16]
When using BearerType tokens I expected that I had to prefix my JWT token with `Bearer`, but this leads to the following:

**401 Unauthorized**
```json
{
	"status_code": 401,
	"detail": "Invalid token"
}
```

In addition, when trying the endpoints in swagger I get the same error from the "auto-generated" requests:
```
curl -X 'GET' \
  'http://localhost:8000/test' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Njc1MTA2NTQsImlhdCI6MTY2NzQyNDI1NCwic3ViIjoiMTIzIn0.D62lYlC6sDl5wVY3I1MpUSwPfYwM9rdykMQ_-9ofAgM'
  ```

**Comment by Goldziher** [comment]
Thank you for reporting it. @cofin can you handle this?

**Comment by cofin** [comment]
Yep.  I'll take a look this afternoon.
